server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:file:~/rumahittes
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false 
  main:
    allow-bean-definition-overriding: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

path:
  location: C:/alpabit/Project/csv/
